---
- name: Ensure HAProxy is installed.
  package: name=haproxy state=present

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: Gather package facts
  package_facts:
    manager: auto

- name: Get HAProxy version
  set_fact:
    haproxy_version: "{{ ansible_facts.packages['haproxy'][0]['version'] }}"

- debug: var=haproxy_version verbosity=1

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- include: logging.yml

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
